env:
  global:
    - CC_TEST_REPORTER_ID=096ba16607d2096f89d2d8f8d4d6e459ac0ebf4dcdf06cdb8305f7c697c43723
language: java
jdk:
  - oraclejdk8
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn verify -B
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
